# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
set_msg_config  -id {BD 41-759}  -new_severity {INFO} 
set_msg_config  -id {BD 41-759}  -new_severity {CRITICAL WARNING} 

create_project -in_memory -part xc7z020clg400-1
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/MA_1/Basic_DMT/netlistFinishDMT2/ip_catalog/basic_dmt.cache/wt [current_project]
set_property parent.project_path D:/MA_1/Basic_DMT/netlistFinishDMT2/ip_catalog/basic_dmt.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part em.avnet.com:microzed_7020:part0:1.0 [current_project]
set_property ip_repo_paths D:/MA_1/Basic_DMT/netlistFinishDMT2/ip [current_project]
add_files -quiet D:/MA_1/Basic_DMT/netlistFinishDMT2/ip_catalog/basic_dmt.runs/basic_dmt_0_synth_1/basic_dmt_0.dcp
set_property used_in_implementation false [get_files D:/MA_1/Basic_DMT/netlistFinishDMT2/ip_catalog/basic_dmt.runs/basic_dmt_0_synth_1/basic_dmt_0.dcp]
add_files D:/MA_1/Basic_DMT/netlistFinishDMT2/ip_catalog/basic_dmt.srcs/sources_1/bd/basic_dmt_bd/basic_dmt_bd.bd
set_property used_in_implementation false [get_files -all d:/MA_1/Basic_DMT/netlistFinishDMT2/ip_catalog/basic_dmt.srcs/sources_1/bd/basic_dmt_bd/ip/basic_dmt_bd_basic_dmt_1_0/basic_dmt_c_counter_binary_v12_0_0/basic_dmt_c_counter_binary_v12_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/MA_1/Basic_DMT/netlistFinishDMT2/ip_catalog/basic_dmt.srcs/sources_1/bd/basic_dmt_bd/ip/basic_dmt_bd_basic_dmt_1_0/basic_dmt_fifo_generator_v12_0_0/basic_dmt_fifo_generator_v12_0_0/basic_dmt_fifo_generator_v12_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/MA_1/Basic_DMT/netlistFinishDMT2/ip_catalog/basic_dmt.srcs/sources_1/bd/basic_dmt_bd/ip/basic_dmt_bd_basic_dmt_1_0/basic_dmt_fifo_generator_v12_0_0/basic_dmt_fifo_generator_v12_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/MA_1/Basic_DMT/netlistFinishDMT2/ip_catalog/basic_dmt.srcs/sources_1/bd/basic_dmt_bd/ip/basic_dmt_bd_basic_dmt_1_0/basic_dmt_fifo_generator_v12_0_1/basic_dmt_fifo_generator_v12_0_1/basic_dmt_fifo_generator_v12_0_1.xdc]
set_property used_in_implementation false [get_files -all d:/MA_1/Basic_DMT/netlistFinishDMT2/ip_catalog/basic_dmt.srcs/sources_1/bd/basic_dmt_bd/ip/basic_dmt_bd_basic_dmt_1_0/basic_dmt_fifo_generator_v12_0_1/basic_dmt_fifo_generator_v12_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/MA_1/Basic_DMT/netlistFinishDMT2/ip_catalog/basic_dmt.srcs/sources_1/bd/basic_dmt_bd/ip/basic_dmt_bd_basic_dmt_1_0/basic_dmt_fifo_generator_v12_0_2/basic_dmt_fifo_generator_v12_0_2/basic_dmt_fifo_generator_v12_0_2.xdc]
set_property used_in_implementation false [get_files -all d:/MA_1/Basic_DMT/netlistFinishDMT2/ip_catalog/basic_dmt.srcs/sources_1/bd/basic_dmt_bd/ip/basic_dmt_bd_basic_dmt_1_0/basic_dmt_fifo_generator_v12_0_2/basic_dmt_fifo_generator_v12_0_2_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/MA_1/Basic_DMT/netlistFinishDMT2/ip_catalog/basic_dmt.srcs/sources_1/bd/basic_dmt_bd/ip/basic_dmt_bd_basic_dmt_1_0/basic_dmt_fifo_generator_v12_0_3/basic_dmt_fifo_generator_v12_0_3/basic_dmt_fifo_generator_v12_0_3.xdc]
set_property used_in_implementation false [get_files -all d:/MA_1/Basic_DMT/netlistFinishDMT2/ip_catalog/basic_dmt.srcs/sources_1/bd/basic_dmt_bd/ip/basic_dmt_bd_basic_dmt_1_0/basic_dmt_fifo_generator_v12_0_3/basic_dmt_fifo_generator_v12_0_3_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/MA_1/Basic_DMT/netlistFinishDMT2/ip_catalog/basic_dmt.srcs/sources_1/bd/basic_dmt_bd/ip/basic_dmt_bd_basic_dmt_1_0/basic_dmt_fifo_generator_v12_0_4/basic_dmt_fifo_generator_v12_0_4/basic_dmt_fifo_generator_v12_0_4.xdc]
set_property used_in_implementation false [get_files -all d:/MA_1/Basic_DMT/netlistFinishDMT2/ip_catalog/basic_dmt.srcs/sources_1/bd/basic_dmt_bd/ip/basic_dmt_bd_basic_dmt_1_0/basic_dmt_fifo_generator_v12_0_4/basic_dmt_fifo_generator_v12_0_4_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/MA_1/Basic_DMT/netlistFinishDMT2/ip_catalog/basic_dmt.srcs/sources_1/bd/basic_dmt_bd/ip/basic_dmt_bd_basic_dmt_1_0/basic_dmt_xfft_v9_0_0/basic_dmt_xfft_v9_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/MA_1/Basic_DMT/netlistFinishDMT2/ip_catalog/basic_dmt.srcs/sources_1/ipshared/User_Company/basic_dmt_v8_41210/e13c4507/constrs/basic_dmt_clock.xdc]
set_property used_in_implementation false [get_files -all d:/MA_1/Basic_DMT/netlistFinishDMT2/ip_catalog/basic_dmt.srcs/sources_1/ipshared/User_Company/basic_dmt_v8_41210/e13c4507/constrs/basic_dmt.xdc]
set_property used_in_implementation false [get_files -all D:/MA_1/Basic_DMT/netlistFinishDMT2/ip_catalog/basic_dmt.srcs/sources_1/bd/basic_dmt_bd/basic_dmt_bd_ooc.xdc]
set_property is_locked true [get_files D:/MA_1/Basic_DMT/netlistFinishDMT2/ip_catalog/basic_dmt.srcs/sources_1/bd/basic_dmt_bd/basic_dmt_bd.bd]

read_vhdl -library xil_defaultlib {
  D:/MA_1/Basic_DMT/netlistFinishDMT2/ip_catalog/basic_dmt.srcs/sources_1/imports/hdl/basic_dmt_bd_wrapper.vhd
  D:/MA_1/Basic_DMT/netlistFinishDMT2/ip_catalog/basic_dmt.srcs/sources_1/imports/sysgen/basic_dmt_mod.vhd
}
read_xdc D:/MA_1/Basic_DMT/netlistFinishDMT2/ip_catalog/basic_dmt.srcs/constrs_1/new/own.xdc
set_property used_in_implementation false [get_files D:/MA_1/Basic_DMT/netlistFinishDMT2/ip_catalog/basic_dmt.srcs/constrs_1/new/own.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
catch { write_hwdef -file basic_dmt_bd_wrapper.hwdef }
synth_design -top basic_dmt_bd_wrapper -part xc7z020clg400-1
write_checkpoint -noxdef basic_dmt_bd_wrapper.dcp
catch { report_utilization -file basic_dmt_bd_wrapper_utilization_synth.rpt -pb basic_dmt_bd_wrapper_utilization_synth.pb }
