# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/own.xdc

# Block Designs: bd/basic_dmt_bd/basic_dmt_bd.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==basic_dmt_bd || ORIG_REF_NAME==basic_dmt_bd}]

# IP: bd/basic_dmt_bd/ip/basic_dmt_bd_basic_dmt_1_0/basic_dmt_bd_basic_dmt_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==basic_dmt_bd_basic_dmt_1_0 || ORIG_REF_NAME==basic_dmt_bd_basic_dmt_1_0}]

# IP: bd/basic_dmt_bd/ip/basic_dmt_bd_basic_dmt_1_0/basic_dmt_c_counter_binary_v12_0_0/basic_dmt_c_counter_binary_v12_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==basic_dmt_c_counter_binary_v12_0_0 || ORIG_REF_NAME==basic_dmt_c_counter_binary_v12_0_0}]

# IP: bd/basic_dmt_bd/ip/basic_dmt_bd_basic_dmt_1_0/basic_dmt_fifo_generator_v12_0_0/basic_dmt_fifo_generator_v12_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==basic_dmt_fifo_generator_v12_0_0 || ORIG_REF_NAME==basic_dmt_fifo_generator_v12_0_0}]

# IP: bd/basic_dmt_bd/ip/basic_dmt_bd_basic_dmt_1_0/basic_dmt_fifo_generator_v12_0_1/basic_dmt_fifo_generator_v12_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==basic_dmt_fifo_generator_v12_0_1 || ORIG_REF_NAME==basic_dmt_fifo_generator_v12_0_1}]

# IP: bd/basic_dmt_bd/ip/basic_dmt_bd_basic_dmt_1_0/basic_dmt_fifo_generator_v12_0_2/basic_dmt_fifo_generator_v12_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==basic_dmt_fifo_generator_v12_0_2 || ORIG_REF_NAME==basic_dmt_fifo_generator_v12_0_2}]

# IP: bd/basic_dmt_bd/ip/basic_dmt_bd_basic_dmt_1_0/basic_dmt_fifo_generator_v12_0_3/basic_dmt_fifo_generator_v12_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==basic_dmt_fifo_generator_v12_0_3 || ORIG_REF_NAME==basic_dmt_fifo_generator_v12_0_3}]

# IP: bd/basic_dmt_bd/ip/basic_dmt_bd_basic_dmt_1_0/basic_dmt_fifo_generator_v12_0_4/basic_dmt_fifo_generator_v12_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==basic_dmt_fifo_generator_v12_0_4 || ORIG_REF_NAME==basic_dmt_fifo_generator_v12_0_4}]

# IP: bd/basic_dmt_bd/ip/basic_dmt_bd_basic_dmt_1_0/basic_dmt_xfft_v9_0_0/basic_dmt_xfft_v9_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==basic_dmt_xfft_v9_0_0 || ORIG_REF_NAME==basic_dmt_xfft_v9_0_0}]

# XDC: bd/basic_dmt_bd/ip/basic_dmt_bd_basic_dmt_1_0/basic_dmt_c_counter_binary_v12_0_0/basic_dmt_c_counter_binary_v12_0_0_ooc.xdc

# XDC: bd/basic_dmt_bd/ip/basic_dmt_bd_basic_dmt_1_0/basic_dmt_fifo_generator_v12_0_0/basic_dmt_fifo_generator_v12_0_0/basic_dmt_fifo_generator_v12_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==basic_dmt_fifo_generator_v12_0_0 || ORIG_REF_NAME==basic_dmt_fifo_generator_v12_0_0}] {/U0 }]/U0 ]]

# XDC: bd/basic_dmt_bd/ip/basic_dmt_bd_basic_dmt_1_0/basic_dmt_fifo_generator_v12_0_0/basic_dmt_fifo_generator_v12_0_0_ooc.xdc

# XDC: bd/basic_dmt_bd/ip/basic_dmt_bd_basic_dmt_1_0/basic_dmt_fifo_generator_v12_0_1/basic_dmt_fifo_generator_v12_0_1/basic_dmt_fifo_generator_v12_0_1.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==basic_dmt_fifo_generator_v12_0_1 || ORIG_REF_NAME==basic_dmt_fifo_generator_v12_0_1}] {/U0 }]/U0 ]]

# XDC: bd/basic_dmt_bd/ip/basic_dmt_bd_basic_dmt_1_0/basic_dmt_fifo_generator_v12_0_1/basic_dmt_fifo_generator_v12_0_1_ooc.xdc

# XDC: bd/basic_dmt_bd/ip/basic_dmt_bd_basic_dmt_1_0/basic_dmt_fifo_generator_v12_0_2/basic_dmt_fifo_generator_v12_0_2/basic_dmt_fifo_generator_v12_0_2.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==basic_dmt_fifo_generator_v12_0_2 || ORIG_REF_NAME==basic_dmt_fifo_generator_v12_0_2}] {/U0 }]/U0 ]]

# XDC: bd/basic_dmt_bd/ip/basic_dmt_bd_basic_dmt_1_0/basic_dmt_fifo_generator_v12_0_2/basic_dmt_fifo_generator_v12_0_2_ooc.xdc

# XDC: bd/basic_dmt_bd/ip/basic_dmt_bd_basic_dmt_1_0/basic_dmt_fifo_generator_v12_0_3/basic_dmt_fifo_generator_v12_0_3/basic_dmt_fifo_generator_v12_0_3.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==basic_dmt_fifo_generator_v12_0_3 || ORIG_REF_NAME==basic_dmt_fifo_generator_v12_0_3}] {/U0 }]/U0 ]]

# XDC: bd/basic_dmt_bd/ip/basic_dmt_bd_basic_dmt_1_0/basic_dmt_fifo_generator_v12_0_3/basic_dmt_fifo_generator_v12_0_3_ooc.xdc

# XDC: bd/basic_dmt_bd/ip/basic_dmt_bd_basic_dmt_1_0/basic_dmt_fifo_generator_v12_0_4/basic_dmt_fifo_generator_v12_0_4/basic_dmt_fifo_generator_v12_0_4.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==basic_dmt_fifo_generator_v12_0_4 || ORIG_REF_NAME==basic_dmt_fifo_generator_v12_0_4}] {/U0 }]/U0 ]]

# XDC: bd/basic_dmt_bd/ip/basic_dmt_bd_basic_dmt_1_0/basic_dmt_fifo_generator_v12_0_4/basic_dmt_fifo_generator_v12_0_4_ooc.xdc

# XDC: bd/basic_dmt_bd/ip/basic_dmt_bd_basic_dmt_1_0/basic_dmt_xfft_v9_0_0/basic_dmt_xfft_v9_0_0_ooc.xdc

# XDC: ipshared/User_Company/basic_dmt_v8_41210/e13c4507/constrs/basic_dmt_clock.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==basic_dmt_bd_basic_dmt_1_0 || ORIG_REF_NAME==basic_dmt_bd_basic_dmt_1_0}] {/U0 }]/U0 ]]

# XDC: ipshared/User_Company/basic_dmt_v8_41210/e13c4507/constrs/basic_dmt.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==basic_dmt_bd_basic_dmt_1_0 || ORIG_REF_NAME==basic_dmt_bd_basic_dmt_1_0}] {/U0 }]/U0 ]]

# XDC: bd/basic_dmt_bd/basic_dmt_bd_ooc.xdc
