# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/MA_1/Basic_DMT/netlistFinishDMT2/ip_catalog/basic_dmt.srcs/sources_1/ip/basic_dmt_0/basic_dmt_0.xci
# IP: The module: 'basic_dmt_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/MA_1/Basic_DMT/netlistFinishDMT2/ip_catalog/basic_dmt.srcs/sources_1/ip/basic_dmt_0/basic_dmt_c_counter_binary_v12_0_0/basic_dmt_c_counter_binary_v12_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==basic_dmt_c_counter_binary_v12_0_0 || ORIG_REF_NAME==basic_dmt_c_counter_binary_v12_0_0}]

# IP: d:/MA_1/Basic_DMT/netlistFinishDMT2/ip_catalog/basic_dmt.srcs/sources_1/ip/basic_dmt_0/basic_dmt_fifo_generator_v12_0_0/basic_dmt_fifo_generator_v12_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==basic_dmt_fifo_generator_v12_0_0 || ORIG_REF_NAME==basic_dmt_fifo_generator_v12_0_0}]

# IP: d:/MA_1/Basic_DMT/netlistFinishDMT2/ip_catalog/basic_dmt.srcs/sources_1/ip/basic_dmt_0/basic_dmt_fifo_generator_v12_0_1/basic_dmt_fifo_generator_v12_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==basic_dmt_fifo_generator_v12_0_1 || ORIG_REF_NAME==basic_dmt_fifo_generator_v12_0_1}]

# IP: d:/MA_1/Basic_DMT/netlistFinishDMT2/ip_catalog/basic_dmt.srcs/sources_1/ip/basic_dmt_0/basic_dmt_fifo_generator_v12_0_2/basic_dmt_fifo_generator_v12_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==basic_dmt_fifo_generator_v12_0_2 || ORIG_REF_NAME==basic_dmt_fifo_generator_v12_0_2}]

# IP: d:/MA_1/Basic_DMT/netlistFinishDMT2/ip_catalog/basic_dmt.srcs/sources_1/ip/basic_dmt_0/basic_dmt_fifo_generator_v12_0_3/basic_dmt_fifo_generator_v12_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==basic_dmt_fifo_generator_v12_0_3 || ORIG_REF_NAME==basic_dmt_fifo_generator_v12_0_3}]

# IP: d:/MA_1/Basic_DMT/netlistFinishDMT2/ip_catalog/basic_dmt.srcs/sources_1/ip/basic_dmt_0/basic_dmt_fifo_generator_v12_0_4/basic_dmt_fifo_generator_v12_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==basic_dmt_fifo_generator_v12_0_4 || ORIG_REF_NAME==basic_dmt_fifo_generator_v12_0_4}]

# IP: d:/MA_1/Basic_DMT/netlistFinishDMT2/ip_catalog/basic_dmt.srcs/sources_1/ip/basic_dmt_0/basic_dmt_xfft_v9_0_0/basic_dmt_xfft_v9_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==basic_dmt_xfft_v9_0_0 || ORIG_REF_NAME==basic_dmt_xfft_v9_0_0}]

# XDC: d:/MA_1/Basic_DMT/netlistFinishDMT2/ip_catalog/basic_dmt.srcs/sources_1/ip/basic_dmt_0/basic_dmt_c_counter_binary_v12_0_0/basic_dmt_c_counter_binary_v12_0_0_ooc.xdc

# XDC: d:/MA_1/Basic_DMT/netlistFinishDMT2/ip_catalog/basic_dmt.srcs/sources_1/ip/basic_dmt_0/basic_dmt_fifo_generator_v12_0_0/basic_dmt_fifo_generator_v12_0_0/basic_dmt_fifo_generator_v12_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==basic_dmt_fifo_generator_v12_0_0 || ORIG_REF_NAME==basic_dmt_fifo_generator_v12_0_0}] {/U0 }]/U0 ]]

# XDC: d:/MA_1/Basic_DMT/netlistFinishDMT2/ip_catalog/basic_dmt.srcs/sources_1/ip/basic_dmt_0/basic_dmt_fifo_generator_v12_0_0/basic_dmt_fifo_generator_v12_0_0_ooc.xdc

# XDC: d:/MA_1/Basic_DMT/netlistFinishDMT2/ip_catalog/basic_dmt.srcs/sources_1/ip/basic_dmt_0/basic_dmt_fifo_generator_v12_0_1/basic_dmt_fifo_generator_v12_0_1/basic_dmt_fifo_generator_v12_0_1.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==basic_dmt_fifo_generator_v12_0_1 || ORIG_REF_NAME==basic_dmt_fifo_generator_v12_0_1}] {/U0 }]/U0 ]]

# XDC: d:/MA_1/Basic_DMT/netlistFinishDMT2/ip_catalog/basic_dmt.srcs/sources_1/ip/basic_dmt_0/basic_dmt_fifo_generator_v12_0_1/basic_dmt_fifo_generator_v12_0_1_ooc.xdc

# XDC: d:/MA_1/Basic_DMT/netlistFinishDMT2/ip_catalog/basic_dmt.srcs/sources_1/ip/basic_dmt_0/basic_dmt_fifo_generator_v12_0_2/basic_dmt_fifo_generator_v12_0_2/basic_dmt_fifo_generator_v12_0_2.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==basic_dmt_fifo_generator_v12_0_2 || ORIG_REF_NAME==basic_dmt_fifo_generator_v12_0_2}] {/U0 }]/U0 ]]

# XDC: d:/MA_1/Basic_DMT/netlistFinishDMT2/ip_catalog/basic_dmt.srcs/sources_1/ip/basic_dmt_0/basic_dmt_fifo_generator_v12_0_2/basic_dmt_fifo_generator_v12_0_2_ooc.xdc

# XDC: d:/MA_1/Basic_DMT/netlistFinishDMT2/ip_catalog/basic_dmt.srcs/sources_1/ip/basic_dmt_0/basic_dmt_fifo_generator_v12_0_3/basic_dmt_fifo_generator_v12_0_3/basic_dmt_fifo_generator_v12_0_3.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==basic_dmt_fifo_generator_v12_0_3 || ORIG_REF_NAME==basic_dmt_fifo_generator_v12_0_3}] {/U0 }]/U0 ]]

# XDC: d:/MA_1/Basic_DMT/netlistFinishDMT2/ip_catalog/basic_dmt.srcs/sources_1/ip/basic_dmt_0/basic_dmt_fifo_generator_v12_0_3/basic_dmt_fifo_generator_v12_0_3_ooc.xdc

# XDC: d:/MA_1/Basic_DMT/netlistFinishDMT2/ip_catalog/basic_dmt.srcs/sources_1/ip/basic_dmt_0/basic_dmt_fifo_generator_v12_0_4/basic_dmt_fifo_generator_v12_0_4/basic_dmt_fifo_generator_v12_0_4.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==basic_dmt_fifo_generator_v12_0_4 || ORIG_REF_NAME==basic_dmt_fifo_generator_v12_0_4}] {/U0 }]/U0 ]]

# XDC: d:/MA_1/Basic_DMT/netlistFinishDMT2/ip_catalog/basic_dmt.srcs/sources_1/ip/basic_dmt_0/basic_dmt_fifo_generator_v12_0_4/basic_dmt_fifo_generator_v12_0_4_ooc.xdc

# XDC: d:/MA_1/Basic_DMT/netlistFinishDMT2/ip_catalog/basic_dmt.srcs/sources_1/ip/basic_dmt_0/basic_dmt_xfft_v9_0_0/basic_dmt_xfft_v9_0_0_ooc.xdc

# XDC: d:/MA_1/Basic_DMT/netlistFinishDMT2/ip_catalog/basic_dmt.srcs/sources_1/ip/basic_dmt_0/constrs/basic_dmt_clock.xdc
# XDC: The top module name and the constraint reference have the same name: 'basic_dmt_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: d:/MA_1/Basic_DMT/netlistFinishDMT2/ip_catalog/basic_dmt.srcs/sources_1/ip/basic_dmt_0/constrs/basic_dmt.xdc
# XDC: The top module name and the constraint reference have the same name: 'basic_dmt_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: D:/MA_1/Basic_DMT/netlistFinishDMT2/ip_catalog/basic_dmt.srcs/sources_1/ip/basic_dmt_0/basic_dmt_0.xci
# IP: The module: 'basic_dmt_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/MA_1/Basic_DMT/netlistFinishDMT2/ip_catalog/basic_dmt.srcs/sources_1/ip/basic_dmt_0/basic_dmt_c_counter_binary_v12_0_0/basic_dmt_c_counter_binary_v12_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==basic_dmt_c_counter_binary_v12_0_0 || ORIG_REF_NAME==basic_dmt_c_counter_binary_v12_0_0}]

# IP: d:/MA_1/Basic_DMT/netlistFinishDMT2/ip_catalog/basic_dmt.srcs/sources_1/ip/basic_dmt_0/basic_dmt_fifo_generator_v12_0_0/basic_dmt_fifo_generator_v12_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==basic_dmt_fifo_generator_v12_0_0 || ORIG_REF_NAME==basic_dmt_fifo_generator_v12_0_0}]

# IP: d:/MA_1/Basic_DMT/netlistFinishDMT2/ip_catalog/basic_dmt.srcs/sources_1/ip/basic_dmt_0/basic_dmt_fifo_generator_v12_0_1/basic_dmt_fifo_generator_v12_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==basic_dmt_fifo_generator_v12_0_1 || ORIG_REF_NAME==basic_dmt_fifo_generator_v12_0_1}]

# IP: d:/MA_1/Basic_DMT/netlistFinishDMT2/ip_catalog/basic_dmt.srcs/sources_1/ip/basic_dmt_0/basic_dmt_fifo_generator_v12_0_2/basic_dmt_fifo_generator_v12_0_2.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==basic_dmt_fifo_generator_v12_0_2 || ORIG_REF_NAME==basic_dmt_fifo_generator_v12_0_2}]

# IP: d:/MA_1/Basic_DMT/netlistFinishDMT2/ip_catalog/basic_dmt.srcs/sources_1/ip/basic_dmt_0/basic_dmt_fifo_generator_v12_0_3/basic_dmt_fifo_generator_v12_0_3.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==basic_dmt_fifo_generator_v12_0_3 || ORIG_REF_NAME==basic_dmt_fifo_generator_v12_0_3}]

# IP: d:/MA_1/Basic_DMT/netlistFinishDMT2/ip_catalog/basic_dmt.srcs/sources_1/ip/basic_dmt_0/basic_dmt_fifo_generator_v12_0_4/basic_dmt_fifo_generator_v12_0_4.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==basic_dmt_fifo_generator_v12_0_4 || ORIG_REF_NAME==basic_dmt_fifo_generator_v12_0_4}]

# IP: d:/MA_1/Basic_DMT/netlistFinishDMT2/ip_catalog/basic_dmt.srcs/sources_1/ip/basic_dmt_0/basic_dmt_xfft_v9_0_0/basic_dmt_xfft_v9_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==basic_dmt_xfft_v9_0_0 || ORIG_REF_NAME==basic_dmt_xfft_v9_0_0}]

# XDC: d:/MA_1/Basic_DMT/netlistFinishDMT2/ip_catalog/basic_dmt.srcs/sources_1/ip/basic_dmt_0/basic_dmt_c_counter_binary_v12_0_0/basic_dmt_c_counter_binary_v12_0_0_ooc.xdc

# XDC: d:/MA_1/Basic_DMT/netlistFinishDMT2/ip_catalog/basic_dmt.srcs/sources_1/ip/basic_dmt_0/basic_dmt_fifo_generator_v12_0_0/basic_dmt_fifo_generator_v12_0_0/basic_dmt_fifo_generator_v12_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==basic_dmt_fifo_generator_v12_0_0 || ORIG_REF_NAME==basic_dmt_fifo_generator_v12_0_0}] {/U0 }]/U0 ]]

# XDC: d:/MA_1/Basic_DMT/netlistFinishDMT2/ip_catalog/basic_dmt.srcs/sources_1/ip/basic_dmt_0/basic_dmt_fifo_generator_v12_0_0/basic_dmt_fifo_generator_v12_0_0_ooc.xdc

# XDC: d:/MA_1/Basic_DMT/netlistFinishDMT2/ip_catalog/basic_dmt.srcs/sources_1/ip/basic_dmt_0/basic_dmt_fifo_generator_v12_0_1/basic_dmt_fifo_generator_v12_0_1/basic_dmt_fifo_generator_v12_0_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==basic_dmt_fifo_generator_v12_0_1 || ORIG_REF_NAME==basic_dmt_fifo_generator_v12_0_1}] {/U0 }]/U0 ]]

# XDC: d:/MA_1/Basic_DMT/netlistFinishDMT2/ip_catalog/basic_dmt.srcs/sources_1/ip/basic_dmt_0/basic_dmt_fifo_generator_v12_0_1/basic_dmt_fifo_generator_v12_0_1_ooc.xdc

# XDC: d:/MA_1/Basic_DMT/netlistFinishDMT2/ip_catalog/basic_dmt.srcs/sources_1/ip/basic_dmt_0/basic_dmt_fifo_generator_v12_0_2/basic_dmt_fifo_generator_v12_0_2/basic_dmt_fifo_generator_v12_0_2.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==basic_dmt_fifo_generator_v12_0_2 || ORIG_REF_NAME==basic_dmt_fifo_generator_v12_0_2}] {/U0 }]/U0 ]]

# XDC: d:/MA_1/Basic_DMT/netlistFinishDMT2/ip_catalog/basic_dmt.srcs/sources_1/ip/basic_dmt_0/basic_dmt_fifo_generator_v12_0_2/basic_dmt_fifo_generator_v12_0_2_ooc.xdc

# XDC: d:/MA_1/Basic_DMT/netlistFinishDMT2/ip_catalog/basic_dmt.srcs/sources_1/ip/basic_dmt_0/basic_dmt_fifo_generator_v12_0_3/basic_dmt_fifo_generator_v12_0_3/basic_dmt_fifo_generator_v12_0_3.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==basic_dmt_fifo_generator_v12_0_3 || ORIG_REF_NAME==basic_dmt_fifo_generator_v12_0_3}] {/U0 }]/U0 ]]

# XDC: d:/MA_1/Basic_DMT/netlistFinishDMT2/ip_catalog/basic_dmt.srcs/sources_1/ip/basic_dmt_0/basic_dmt_fifo_generator_v12_0_3/basic_dmt_fifo_generator_v12_0_3_ooc.xdc

# XDC: d:/MA_1/Basic_DMT/netlistFinishDMT2/ip_catalog/basic_dmt.srcs/sources_1/ip/basic_dmt_0/basic_dmt_fifo_generator_v12_0_4/basic_dmt_fifo_generator_v12_0_4/basic_dmt_fifo_generator_v12_0_4.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==basic_dmt_fifo_generator_v12_0_4 || ORIG_REF_NAME==basic_dmt_fifo_generator_v12_0_4}] {/U0 }]/U0 ]]

# XDC: d:/MA_1/Basic_DMT/netlistFinishDMT2/ip_catalog/basic_dmt.srcs/sources_1/ip/basic_dmt_0/basic_dmt_fifo_generator_v12_0_4/basic_dmt_fifo_generator_v12_0_4_ooc.xdc

# XDC: d:/MA_1/Basic_DMT/netlistFinishDMT2/ip_catalog/basic_dmt.srcs/sources_1/ip/basic_dmt_0/basic_dmt_xfft_v9_0_0/basic_dmt_xfft_v9_0_0_ooc.xdc

# XDC: d:/MA_1/Basic_DMT/netlistFinishDMT2/ip_catalog/basic_dmt.srcs/sources_1/ip/basic_dmt_0/constrs/basic_dmt_clock.xdc
# XDC: The top module name and the constraint reference have the same name: 'basic_dmt_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: d:/MA_1/Basic_DMT/netlistFinishDMT2/ip_catalog/basic_dmt.srcs/sources_1/ip/basic_dmt_0/constrs/basic_dmt.xdc
# XDC: The top module name and the constraint reference have the same name: 'basic_dmt_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
