# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/const_xyz.xdc

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1}]

# XDC: bd/design_1/design_1_ooc.xdc
