# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7z020clg400-1
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/project_fred_kombinatorisch/project_fred_muell.cache/wt [current_project]
set_property parent.project_path D:/project_fred_kombinatorisch/project_fred_muell.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part em.avnet.com:microzed_7020:part0:1.0 [current_project]
add_files D:/project_fred_kombinatorisch/project_fred_muell.srcs/sources_1/bd/design_1/design_1.bd
set_property used_in_implementation false [get_files -all D:/project_fred_kombinatorisch/project_fred_muell.srcs/sources_1/bd/design_1/design_1_ooc.xdc]
set_property is_locked true [get_files D:/project_fred_kombinatorisch/project_fred_muell.srcs/sources_1/bd/design_1/design_1.bd]

read_vhdl -library xil_defaultlib D:/project_fred_kombinatorisch/project_fred_muell.srcs/sources_1/new/toggle.vhd
read_xdc D:/project_fred_kombinatorisch/project_fred_muell.srcs/constrs_1/new/const_xyz.xdc
set_property used_in_implementation false [get_files D:/project_fred_kombinatorisch/project_fred_muell.srcs/constrs_1/new/const_xyz.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
catch { write_hwdef -file toggle.hwdef }
synth_design -top toggle -part xc7z020clg400-1
write_checkpoint -noxdef toggle.dcp
catch { report_utilization -file toggle_utilization_synth.rpt -pb toggle_utilization_synth.pb }
